server:
  #端口号
  port: 8081

wx:
  #微信id和密钥,修改这里
  wxId: wx70a9cccf42******
  wxSecret: 2e9481013bc3b00fbfbde4c214******

oss:
  #oss配置 修改这里
  ossId: 123
  ossSecret: 456

spring:
  #启动程序后出现的登录账户和密码
  security:
    user:
      name: 123
      password: 123
  datasource:
    #数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/share?useUnicode=true&useSSL=true&characterEncoding=utf8
    username: 账号
    password: 密码
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器地址
    host: 127.0.0.1
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        #spring.redis.pool.max-active=8
        max-active: 8
        ## 连接池中的最大空闲连接
        #spring.redis.pool.max-idle=8
        max-idle: 8
        ## 连接池中的最小空闲连接
        #spring.redis.pool.min-idle=0
        min-idle: 0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    view:
      # 页面默认前缀目录
      prefix: /WEB-INF/
      # 响应页面默认后缀
      suffix: .jsp

swagger:
  title: API标题
  description: API描述
  version: 1.0
  terms-of-service-url: https://www.huangxin.work/
  base-package: work.huangxin.share
  contact:
    name: xin-felix
    url: https://www.huangxin.work/
    email: 1538933906@qq.com

#jwt配置
audience:
  # 代表这个JWT的接收对象,存入audience
  clientId: 660CF47C788E8609E6D35E3CFCD645DA
  # 密钥, 经过Base64加密, 可自行替换
  base64Secret: NjYwQ0Y0N0M3ODhFODYwOUU2RDM1RTNDRkNENjQ1REE=
  # JWT的签发主体，存入issuer
  name: huangxin
  # 过期时间，时间戳
  expiresSecond: 172800

mybatis:
  type-aliases-package: work.huangxin.share.model
  mapper-locations: classpath:mappers/*.xml
  #通用mapper配置
  mapper:
    #公用接口类路径
    mappers: work.huangxin.share.basemapper
    identity: MYSQL

logging:
  level:
    work.huangxin.share.mapper: debug

spring.jackson.date-format: yyyy-MM-dd HH:mm

#这个是时区，一定要加，否则会默认为格林尼治时间，即少8小时
spring.jackson.time-zone: GMT+8
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
